# Generated by Django 2.1.15 on 2021-11-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicActivity',
            fields=[
                ('aca_activity_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('aca_activity_name', models.CharField(max_length=30)),
                ('aca_student_id', models.CharField(max_length=30)),
                ('aca_activity_location', models.CharField(max_length=30)),
                ('aca_activity_date', models.DateField()),
                ('aca_report_name_zh', models.CharField(max_length=30)),
                ('aca_report_name_en', models.CharField(max_length=50)),
                ('aca_evidentiary_material', models.CharField(max_length=50)),
                ('aca_audit_situation', models.CharField(max_length=20)),
                ('aca_extra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcheievementIndex',
            fields=[
                ('ache_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ache_stu_if', models.CharField(max_length=30)),
                ('ache_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ache_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bo_name', models.CharField(max_length=50)),
                ('bo_pub', models.CharField(max_length=50)),
                ('bo_time', models.DateField()),
                ('bo_rank', models.IntegerField()),
                ('bo_evidence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_hours', models.CharField(max_length=50)),
                ('course_scores', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=50)),
                ('course_academy', models.CharField(max_length=50)),
                ('course_subject', models.CharField(max_length=50)),
                ('course_teacher_id', models.CharField(max_length=30)),
                ('course_schedule', models.CharField(max_length=50)),
                ('course_assessment_method', models.CharField(max_length=50)),
                ('course_nature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('ache_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pa_name', models.CharField(max_length=50)),
                ('pa_rank', models.IntegerField()),
                ('pa_time', models.DateField()),
                ('pa_state', models.IntegerField()),
                ('p_evidence', models.CharField(max_length=50)),
                ('p_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pro_type', models.CharField(max_length=30)),
                ('pro_name', models.CharField(max_length=30)),
                ('pro_tutor_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ache_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rep_name', models.CharField(max_length=50)),
                ('rep_port', models.CharField(max_length=50)),
                ('rep_time', models.DateField()),
                ('rep_num', models.IntegerField()),
                ('rep_evidence', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('ache_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('re_name', models.CharField(max_length=50)),
                ('re_level', models.CharField(max_length=50)),
                ('re_grade', models.CharField(max_length=50)),
                ('re_num', models.IntegerField()),
                ('re_time', models.DateField()),
                ('re_evidence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_subject', models.CharField(max_length=30)),
                ('stu_sex', models.CharField(max_length=1)),
                ('stu_type', models.CharField(max_length=10)),
                ('stu_tutor_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_sex', models.CharField(max_length=1)),
                ('teacher_funds', models.DecimalField(decimal_places=1, max_digits=6)),
                ('teacher_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('log_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('log_pwd', models.CharField(max_length=30)),
                ('log_type', models.CharField(max_length=30)),
            ],
        ),
    ]
